pipeline:
  npm_install:
    image: node:8.0
    commands:
      - env
      - yarn
      - yarn test
  publish:
    image: plugins/docker
    username: josmo
    secrets: [ docker_password ]
    repo: peloton/aws-pricing-api
    auto_tag: true
    file: Dockerfile
    when:
      event: [ push, tag ]

  deploy:
    image: peloton/drone-rancher
    url: http://rancher.seattleslow.com
    access_key: 845E1894659FB1248837
    secrets: [ rancher_secret_key ]
    service: spot/aws-pricing-api
    docker_image: peloton/aws-pricing-api:${DRONE_TAG}
    start_first: false
    confirm: true
    timeout: 180
    when:
      local: false
      event: tag
