pipeline:
  npm_install:
    image: node:9.11.1
    commands:
      - env
      - yarn
      - yarn test
      - yarn build
  publish:
    image: plugins/docker
    username: josmo
    secrets: [ docker_password ]
    repo: peloton/aws-pricing-api
    auto_tag: true
    file: Dockerfile
    when:
      event: [ push, tag ]

  deploy-tag:
    image: peloton/drone-helm:0.0.3
    chart: ./helm/aws-pricing-api
    update_dependencies: true
    values:
    - image.tag=${DRONE_TAG}
    release: classis-pricing
    namespace: classis
    wait: true
    timeout: 200
    secrets: [ api_server, kubernetes_token ]
    when:
      event: [ tag ]
      branch: master

