
version: '2'
services:
  app:
    image: rcflaherty/aws-pricing-api:latest
    environment:
    - NODE_ENV=docker-compose
    ports:
    - 3000:3000
    depends_on:
    - database
    volumes:
    - ./:/usr/src/app
    - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start
  database:
    image: mongo:3.2.15
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    mem_limit: 5g
