
version: '3'
services:
  app:
    build: .
    environment:
    - NODE_ENV=docker-compose
    ports:
    - 3000:3000
    depends_on:
    - database
  database:
    image: mongo:3.2.15
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
